# Generated by Django 4.2.16 on 2024-09-22 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=10000, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('especialidade', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=10000, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id_pet', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('especie', models.CharField(max_length=1000)),
                ('idade', models.IntegerField()),
                ('dono_do_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_consulta', models.DateTimeField(null=True)),
                ('realizada', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.pet')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstore.veterinario')),
            ],
        ),
    ]
