# Generated by Django 4.2.16 on 2024-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.CharField(max_length=191, unique=True),
        ),
    ]
