# Generated by Django 4.2.16 on 2024-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0002_alter_usuario_email_alter_veterinario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
