# Generated by Django 4.2.16 on 2024-09-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0003_alter_pet_especie_alter_pet_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
