# Generated by Django 4.2.16 on 2024-10-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstore', '0005_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='senha',
            field=models.CharField(max_length=200),
        ),
    ]
